octoenergy/tentaclio

Makefile, setup.py
Modify setup.py and Makefile to have the release ready.
=> Finilise first release

CHANGELOG.txt, setup.py
Test automatic release process
=> Test release

src/tentaclio/__init__.py, src/tentaclio/hooks/__init__.py, src/tentaclio/protocols.py
=> Rename octo-io to tentaclio

src/tentaclio/fs/api.py, tests/unit/fs/test_api.py
give support os.listdir like functionality to tentaclio
=> Add listdir

src/tentaclio/__init__.py, src/tentaclio/clients/__init__.py, src/tentaclio/clients/local_fs_client.py, src/tentaclio/fs/scanners.py, src/tentaclio/handlers/file_handler.py, src/tentaclio/handlers/stream_handler.py, tests/unit/clients/test_local_fs_client.py, tests/unit/fs/test_scanners.py, tests/unit/handlers/test_file_handler.py
Create a local client rather than creating local fs specific handlers
for streams/scandir/etc....
=> Add LocalFSClient rather than handler specific classes

src/tentaclio/__init__.py, src/tentaclio/clients/local_fs_client.py, src/tentaclio/clients/s3_client.py, src/tentaclio/fs/__init__.py, src/tentaclio/fs/api.py, src/tentaclio/fs/remover.py, tests/functional/s3/test_fs.py, tests/unit/fs/test_remover.py
=> Add copy support

CHANGELOG.txt, README.md, setup.py
=> Release 0.0.1.alpha.4

CHANGELOG.txt, setup.py, src/tentaclio/clients/ftp_client.py
The command used might not be implemented
=> Do not check filetype before retrieval in ftp

CHANGELOG.txt, README.md, extras/init_tentaclio.sh
As many people struggle with this step maybe it's a good idea to make it
automatic.
=> Add script to setup secrets file

extras/init_tentaclio.sh
A bit more useful and prevents errors
=> Add complete secrets file in init_tentaclio

Pipfile, Pipfile.lock
Twine stopped working in circleci due to a missing dependency
=> Add twine dep

src/tentaclio/clients/postgres_client.py
=> Fix bad python naming

.circleci/config.yml, CHANGELOG.txt, Pipfile, Pipfile.lock, setup.py, src/tentaclio/streams/base_stream.py, tests/unit/streams/test_base_stream.py
Probably it would break in more places but we found that due to change in
zipfile https://github.com/python/cpython/blob/3.7/Lib/zipfile.py#L734 in
python 3.7 using tentaclio to open zip files breaks as it needs a new
seekable method
=> Make base stream seekable

Pipfile.lock, setup.py, src/tentaclio/clients/__init__.py, src/tentaclio/clients/google_drive_client.py, tests/unit/clients/test_google_drive_client.py
This is the first pr of a series. This one
* Creates a dummy google drive client that pre process the path of the url
* Adds the necessary logic to connect using the google api token
=> Add google drive client skeleton

Makefile, src/tentaclio/clients/google_drive_client.py, tests/unit/clients/test_google_drive_client.py
This will allow to call listdir, scandir, and walk for google drive elements. The drive support is still very reduced but I will tackle that in next prs
=> Add scandir support

src/tentaclio/__init__.py, src/tentaclio/clients/google_drive_client.py, src/tentaclio/streams/base_stream.py, tests/unit/clients/test_google_drive_client.py
With this pr we add
* File creation in google drive
* File updates
* Getting the contents of a file
* Registering all the new functionallity to the apis 
* fix small issue to get to_excel working due to change in zipfile in 3.7
=> Allow reading and writting files in google drive

CHANGELOG.txt, Pipfile.lock, setup.py
dataclasses become a std lib module in 3.7, this dep is necessary to 
support 3.6 python versions
=> Add dataclasses package

CHANGELOG.txt, setup.py
- PyAthena version 1.11.1 breaks pulling data from Athena
=> Specify PyAthena version

CHANGELOG.txt, Pipfile.lock, setup.py
=> Update upto latest pandas 1.1.3

.circleci/config.yml, Makefile, Pipfile, Pipfile.lock, setup.py, src/tentaclio/clients/__init__.py, src/tentaclio/clients/http_client.py, src/tentaclio/credentials/reader.py, src/tentaclio/databases/db_registry.py, src/tentaclio/fs/copier.py, src/tentaclio/fs/remover.py, src/tentaclio/fs/scanner.py, src/tentaclio/fs/scanners.py, src/tentaclio/protocols.py, src/tentaclio/streams/base_stream.py, src/tentaclio/streams/csv_db_stream.py, src/tentaclio/streams/stream_client_handler.py, src/tentaclio/streams/stream_registry.py, src/tentaclio/urls.py, tests/unit/clients/test_local_fs_client.py, tests/unit/streams/test_api.py, tests/unit/streams/test_file_handler.py
* Bump to python3.9 and update circleci config
* Unpin dev packages and address type hinting issues
=> Update to python3.9

CHANGELOG.txt, setup.py, src/tentaclio/__init__.py, src/tentaclio/clients/__init__.py, src/tentaclio/clients/importer.py, src/tentaclio/clients/sqla_client.py, src/tentaclio/databases/db_registry.py, src/tentaclio/fs/remover.py, src/tentaclio/fs/scanners.py, src/tentaclio/protocols.py, src/tentaclio/streams/base_stream.py, src/tentaclio/streams/csv_db_stream.py, src/tentaclio/streams/stream_client_handler.py, src/tentaclio/streams/stream_registry.py, tests/functional/sftp/test_api.py, tests/unit/clients/test_importer.py
* Enables automatic loading of installed plugins on initial import
* Enables installing plugins using `tentaclio[plugin]` syntax
=> Automatically import plugins

CHANGELOG.txt, setup.py
Accidentally merged 2 branches both listed as 1.3.3. Updates the latest change to 1.3.4.
=> Bump accidental duplicate version
