- Pipfile.lock
- setup.py
Before this change, a syntax error was causing pipenv's dependency resolution to break.
> Fix requirements in setup.py and update lock file.

- .circleci/config.yml
- Makefile
- setup.cfg
- src/tentaclio/clients/__init__.py
- src/tentaclio/clients/athena_client.py
- src/tentaclio/clients/postgres_client.py
- src/tentaclio/clients/sqla_client.py
- tests/unit/clients/test_athena_client.py
By default, `pyathena` + `sqlalchemy` (as used by our `SQLAlchemyClient`) fetches query results by row.
However, `pyathena` provides a way to fetch results from the `csv` results file created by Athena inside the s3 staging dir by using [`PandasCursor`](https://pypi.org/project/PyAthena/#pandascursor):
- by setting `cursor_class=PandasCursor`  in `connetct_args`, we can speed up all queries run through the client
- by using underlying `cursor`'s `.as_pandas()` method (as done in new `.get_df()`), we can fetch all results from `csv` to a DataFrame even faster, bypassing the row-wise logic.
Example with typical timings for a large query:
```
with tentaclio.db(athena_url) as client:
df = pd.read_sql_query(query, client.conn)
with tentaclio.clients.AthenaClient(tentaclio.credentials.authentica …
```
> Add AthenaClient to allow faster query execution

- src/tentaclio/urls.py
- tests/conftest.py
- tests/unit/clients/test_base_client.py
- tests/unit/clients/test_s3_client.py
- tests/unit/credentials/test_env.py
- tests/unit/credentials/test_injection.py
- tests/unit/credentials/test_reader.py
- tests/unit/handlers/test_stream_handler.py
- tests/unit/test_urls.py
Prior to this change the url class will try to check if the scheme is
supported in the context of tentaclio. Adding more types of registers
will make this check complicated and definitively the url class is not
the place to do it.
> Get rid of scheme support check

- src/tentaclio/clients/__init__.py
- src/tentaclio/clients/base_client.py
- src/tentaclio/clients/ftp_client.py
- src/tentaclio/clients/http_client.py
- src/tentaclio/clients/protocols.py
- src/tentaclio/clients/s3_client.py
- src/tentaclio/clients/sqla_client.py
- src/tentaclio/handlers/stream_handler.py
- src/tentaclio/streams/base_stream.py
- tests/unit/clients/test_s3_client.py
- tests/unit/handlers/test_stream_handler.py
- tests/unit/streams/test_base_stream.py
Before we were using a more OOP approach with clients based on
inheritance. Clients are going to become richer but their features are
going to be more disjoint. i.e S3 client will support streaming and
listing, but not http etc. In order to avoid growing the StreamClient
class and have a more modular design, streaming/listing/querying will be
protocols, allowing to offer the desired functionality per client
without over complicating the inheritance tree.
> Redesign base client

- src/tentaclio/clients/base_client.py
- src/tentaclio/clients/sqla_client.py
We should allow any scheme to not restrict urls that sqlalchemy actually
supports but we are artifically not allowing
> Allow any scheme in the SQLAClient

- CHANGELOG.txt
- setup.py
- src/tentaclio/clients/postgres_client.py
- tests/functional/postgres/test_api.py
- tests/functional/postgres/test_client.py
Streaming results as CSV to STDOUT
```python
import tentaclio as tio
query = "SELECT * FROM table LIMIT 1000000"
url = tio.api.authenticate("postgresql://hostname/db_name")
%%time  # Wall time: 113s
with tio.clients.sqla_client.SQLAlchemyClient(url) as c:
df = c.get_df(query)
%%time  # Wall time: 51s
with tio.clients.postgres_client.PostgresClient(url) as c:
df = c.get_df(query)
```
> Implement PostgresClient.get_df using COPY

- CHANGELOG.txt
- setup.py
Breaking compatibility on `pandas==1.0.2` with regards to IO stream handling.
https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.2.html
https://github.com/pandas-dev/pandas/blob/v1.0.0/pandas/io/parsers.py#L1879
> Restrict pandas version due to incompatibility on IO streams

- CHANGELOG.txt
- setup.py
- src/tentaclio/clients/sqla_client.py
Before this change, params passed to `self.conn.execute` was always an (empty) dict. This is inconsistent with at least some SQLAlchemy clients. After this change, the default value is `params=None`, which works with Postgres and Athena clients.
> Fix `params` kwarg in `SQLAlchemyClient.query()` and `.execute()``

- Pipfile
- Pipfile.lock
- src/tentaclio/clients/http_client.py
- tests/functional/ftp/test_api.py
- tests/functional/s3/test_api.py
- tests/functional/s3/test_fileformat.py
- tests/functional/sftp/test_api.py
This is a pre-update of dependencies when installing google-cloud-storage. So that the linting and testing does not break when it is installed.
When installing google-cloud-storage without locking some dependencies the linting and testing breaks. This can be seen in the branch `gcs-clean-install` in the datavaluepeople fork: [See here](https://github.com/datavaluepeople/tentaclio/tree/gcs-clean-install).
As such it would be great if you guys could look into updating your dependencies as you see fit. 
My recommendations are:
- Updating the `mypy` and `pydocstyle` as there is some issues that would be good to fix there. 
- Updating the `pytest-mock` will need more work as you will have to fix how you are using some mocks in the s3 tests.
> Lock of dependencies and lock file update

- CHANGELOG.txt
- README.md
- setup.py
- src/tentaclio/clients/postgres_client.py
- src/tentaclio/clients/sqla_client.py
- tests/unit/clients/test_postgres_client.py
We've been doing this from the tentaclio file so far. But for dynamic 
systems we need this piece of functionaly to easily filter queries
> Set the pg applicationName from the env

- CHANGELOG.txt
- setup.py
- src/tentaclio/clients/google_drive_client.py
A change in the latest version broke windows compatibility. here the fix grab the right environmental variable when the system is windows.
as per https://superuser.com/questions/607105/is-the-home-environment-variable-normally-set-in-windows
> Use UserProfile instead of HOME in win systems

- CHANGELOG.txt
- Pipfile
- Pipfile.lock
- setup.py
Remove upper constraint on `boto3`.
Prepare library release `v0.0.7`.
> Simplify library dependency tree

- CHANGELOG.txt
- setup.py
- src/tentaclio/credentials/injection.py
- tests/unit/credentials/test_injection.py
Until now were filtering credentials by:
* scheme
* hostname
* path
We have found a usecase where we need to access a resource with different
priviledges, therefore we need to support injecting the right credentials
given the username.
The filtering process takes into account now:
* scheme
* hostname
* path
* username
> Filter credentials by username

- CHANGELOG.txt
- setup.py
- src/tentaclio/clients/google_drive_client.py
- tests/unit/clients/test_google_drive_client.py
There is a case in which we can have access to files withing shared drives
but not have access to the drive itself. As per now we rely on having total
access to the drive to operate we will ignore those shared drives
> Ignore permission errors while geting gdrives

- CHANGELOG.txt
- setup.py
- src/tentaclio/clients/google_drive_client.py
- tests/unit/clients/test_google_drive_client.py
The token from google may come with some extra metada not allowed by the
`Credentials` constructor, filter only those fields that we need to call
the api
> Filter token fields

- src/tentaclio/clients/google_drive_client.py
- tests/unit/clients/test_google_drive_client.py
We have been having some problems with a process that is running papermill that does not have `HOME`. (Bloody GCP DataProc,😒 ). Thus this is a fix if the environment variables are not set for the user profile the current working directory is used.
> Fallback for DEFAULT_TOKEN_FILE

- setup.py
Sqlalchemy 1.4 drops ResultProxy in favour of CursorResult
- https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_1_4_0b1
> Temporarily pin sqlalchemy < 1.4

- CHANGELOG.txt
- setup.py
- Pin `tentaclio-databricks` to thrift version
- Pin pandas <1.4 due to sqlalchemy requirement
https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.4.0.html#backwards-incompatible-api-changes
> Pin databricks + pandas dependencies

- setup.py
`packages_distributions` was introduced in that version and it's being used in the repo
> Require importlib_metadata>3.7

- CHANGELOG.txt
- setup.py
- src/tentaclio/clients/sqla_client.py
- Replace `result.ResultProxy` typehint with `CursorResult`
- From the `CursorResult` docstring:
```
"""A Result that is representing state from a DBAPI cursor.
.. versionchanged:: 1.4  The :class:`.CursorResult` and
:class:`.LegacyCursorResult`
classes replace the previous :class:`.ResultProxy` interface.
These classes are based on the :class:`.Result` calling API
which provides an updated usage model and calling facade for
SQLAlchemy Core and SQLAlchemy ORM.
```
https://docs.sqlalchemy.org/en/14/core/connections.html
> Use sqlalchemy>=1.4

- CHANGELOG.txt
- Pipfile
- Pipfile.lock
- setup.py
- src/tentaclio/streams/base_stream.py
- src/tentaclio/streams/stream_client_handler.py
- tests/unit/clients/test_http_client.py
- tests/unit/streams/test_stream_handler.py
Enables specifying encoding, e.g:
```
with tentaclio.open(url, "r", encoding="latin1") as reader:
df = pd.read_csv(reader)
```
> Allow setting encoding for byte streams

- CHANGELOG.txt
- README.md
- setup.py
- src/tentaclio/protocols.py
- src/tentaclio/streams/api.py
- src/tentaclio/streams/base_stream.py
- src/tentaclio/streams/stream_client_handler.py
- src/tentaclio/streams/stream_registry.py
- tests/unit/streams/test_api.py
- tests/unit/streams/test_base_stream.py
This allows to wrap a writer opened with tentaclio to not flush the buffer
if no writes have been performed
This makes the streamer incompatible with python `open` _but_ it means that
now we can just use the stream when dealing with empty dataframes
``` 
with tio.make_empty_safe(tio.open("s3://blah/file.parquet", mode="wb"))
as f:
if not df.empty:
df.to_parquet(f)
``` 
will not create empty files
> Add make_safe_write function

- CHANGELOG.txt
- setup.py
- src/tentaclio/credentials/__init__.py
- src/tentaclio/credentials/reader.py
- tests/unit/credentials/test_reader.py
Now will get the following errors as a `TentaclioFileError`: 
1. Not found: the file is not in the fs 
2. Missing `secrets:` element 
3. Yaml can't be   parsed: 
File name and error description/line included.
No context is shown in the logs as we would be logging passwords
```
[...]
creds = _load_creds_from_yaml(yaml_reader)
File "/home/javi/src/tentaclio/src/tentaclio/credentials/reader.py", line
66, in _load_creds_from_yaml
raise TentaclioFileError(_process_mark_error(error)) 
tentaclio.credentials.reader.TentaclioFileError:
Your tentaclio secrets file is malformed:
File: /home/javi/src/tentaclio/kk.yml
expected alphabetic or numeric character, but found ' '
in "<file>", line 1, column 2 while scanning an alias
in "<file>", line 1, column 1
```
> Improve credentials parsing errors

- CHANGELOG.txt
- Makefile
- Pipfile
- Pipfile.lock
- setup.py
- src/tentaclio/clients/ftp_client.py
- src/tentaclio/clients/http_client.py
- src/tentaclio/clients/sqla_client.py
- src/tentaclio/hooks/slack_hook.py
- src/tentaclio/streams/api.py
- src/tentaclio/urls.py
- tests/unit/clients/test_decorators.py
- tests/unit/clients/test_ftp_client.py
- tests/unit/clients/test_http_client.py
- tests/unit/credentials/test_api.py
- tests/unit/streams/test_csv_db_stream.py
- tests/unit/streams/test_stream_handler.py
- tests/unit/test_urls.py
Add support for SQLAlchemy 2.0 by correctly handling `sqlalchemy.engine.url.URL`s, which are now immutable.
The only functional changes are in [this commit](https://github.com/octoenergy/tentaclio/commit/b6fff5b0591c9edc7f4c61d8e5b03c90c01de5f5), everything else is linting 😅
> Add sqlalchemy 2 support

- CHANGELOG.txt
- setup.py
- src/tentaclio/clients/sqla_client.py
The `sqlalchemy.engine.url.URL.update_query_string()` method returns a new URL instance, and doesn't update in place:
https://github.com/sqlalchemy/sqlalchemy/blob/fc2bcead435a9bf0a2de8e9b15a1bd835f9d7fe4/lib/sqlalchemy/engine/url.py#L360
We therefore have to overwrite our variable `parsed_url`.
This fixes the bug whereby BigQuery URLs were getting passed without the query params: https://octoenergy.slack.com/archives/C01GPE6BZDJ/p1681975248180199
> Fix update_query_string() returns new URL instance

- CHANGELOG.txt
- Pipfile
- Pipfile.lock
- setup.py
- src/tentaclio/clients/ftp_client.py
- tests/functional/sftp/test_api.py
- tests/unit/clients/test_ftp_client.py
This PR replaces the pysftp dependency with paramiko. pysftp is not supported anymore and hasn't received an update since 2016.
Moving to paramiko allows us to more features, such as adding support for private key authentication, which has also been done in this PR.
> Replace pysftp with paramiko

- CHANGELOG.txt
- README.md
- setup.py
- src/tentaclio/credentials/reader.py
- tests/unit/credentials/test_reader.py
Add environmental variable interpolation support.
If the tentaclio file looks like:
```
secrets:
local_ftp: ftp://${USER}:${PASSWORD}@local.com
```
tentaclio will get the USER and PASSWORD values from the environment
https://app.asana.com/0/1204998866317691/1204977339568190/f
> Add environmental variable interpolation support

- CHANGELOG.txt
- setup.py
- src/tentaclio/credentials/reader.py
- src/tentaclio/urls.py
- tests/unit/credentials/test_reader.py
This PR improves the error messaging around the parsing of the tentaclio secrets. Parsing can fail if secret strings feature special characters. The current error suggests an incorrect IPV6 address however doesn't give an indication of the possible solution, this PR solves that.
Also some small linting fixes
> Improve error message for secret parse error

- CHANGELOG.txt
- setup.py
- src/tentaclio/clients/ftp_client.py
- Fix for 1.3.2 - to enable optional input of private key path and private key password directly to the SFTP client
> Maintain optional input of private key path and private key password

- CHANGELOG.txt
- setup.py
Pins the paramiko dependency version to `<4.0.0` to avoid DSSKey error. Support for DSSKey was [dropped](https://www.paramiko.org/changelog.html) in `v4.0.0`.
Slack [thread](https://krakentech.slack.com/archives/C0853EN8NCA/p1754270831054229)
> Pin paramiko version

- .circleci/config.yml
- CHANGELOG.txt
- Makefile
- Pipfile
- Pipfile.lock
- setup.py
CI `release` step was failing due to a non-specified version requirement of `pkginfo` for `twine`.
- Adds a `check-release` step to CI
- Upgrades the `pgkinfo` package to hopefully [fix](https://github.com/pypi/warehouse/issues/15611) the CI release [issue](https://app.circleci.com/pipelines/github/octoenergy/tentaclio/1141/workflows/74396872-9e1f-406e-afc6-43296dc343dc/jobs/4283) (`check-release` step fails before updating dependency versions)
> Fix tentaclio release

- CHANGELOG.txt
- extras/init_tentaclio.sh
- setup.py
Minor inconvenience:
- previously when this setup script wasn't able to identify the shell type it would exit the script and terminal window meaning the user cannot see any script output
- changing the exit command to a return prevents the terminal termination and allows the user to see the script output
- also improved shell detection
> fix: not identifying shell type exits terminal
